services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jogos_db
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    build: ./RabbitMQ
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 30s


  api1:
    build: ./app
    container_name: api_jogos_1
    restart: always
    environment:
      MONGO_URI: mongodb://mongodb:27017
      DATABASE_NAME: jogos_db
      RABBITMQ_HOST: rabbitmq
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api2:
    build: ./app
    container_name: api_jogos_2
    restart: always
    environment:
      MONGO_URI: mongodb://mongodb:27017
      DATABASE_NAME: jogos_db
      RABBITMQ_HOST: rabbitmq
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  consumer:
    build: ./Consumer
    container_name: worker_consumer
    restart: always
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy

volumes:

  mongo_data:
