# Rate Limit: máximo de 5 requisições por segundo por IP
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
limit_req_status 429;

# Load Balancer alternando entre as duas instâncias do FastAPI
upstream backend_api {
    #least_conn;  # Distribui as requisições para a instância com menos conexões ativas
    #ip_hash;     # Distribui as requisições para a mesma instância com base no IP do cliente
    #weight;      # Distribui as requisições com base em pesos atribuídos às instâncias
    #exemplo de configuração com pesos:
    #server api1:8000 weight=3;  # A instância api1 receberá 3 vezes mais requisições que a instância api2
    #server api2:8000 weight=1;
    #round-robin; # Distribui as requisições de forma circular entre as instâncias (padrão)
    server api1:8000;
    server api2:8000;
}

server {
    listen 80;

    location / {
        limit_req zone=api_limit burst=10 nodelay;

        proxy_pass http://backend_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # Adiciona o endereço IP da instância do FastAPI que respondeu à requisição no cabeçalho da resposta
        add_header X-Upstream-Addr $upstream_addr always;
    }
}